TASK_NOUN_DICT = {
    # libero mem
    'pick the bowl from the plate and place it back 1 time': ['robot', 'bowl 1', 'plate 1'],
    'pick the bowl from the plate and place it back 3 times': ['robot', 'bowl 1', 'plate 1'],
    'pick the bowl from the plate and place it back 5 times': ['robot', 'bowl 1', 'plate 1'],
    'pick the bowl from the plate and place it back 7 times': ['robot', 'bowl 1', 'plate 1'],
    'swap the 3 bowls from left to right using the intermediary plate': ['robot', 'bowl 1', 'plate 1', 'bowl 2', 'plate 2', 'bowl 3', 'plate 3', 'plate 4'],
    'swap the 2 bowls using the intermediary plate': ['robot', 'bowl 1', 'plate 1', 'bowl 2', 'plate 2', 'plate 3'],

    # libero goal
    # 'open the middle drawer of the cabinet': ['robot', 'middle drawer', 'cabinet 1'],
    # 'put the bowl on the stove': ['robot', 'bowl 1', 'stove'],
    # 'put the wine bottle on top of the cabinet': ['robot', 'bottle 1', 'cabinet 1'],
    # 'open the top drawer and put the bowl inside': ['robot', 'top drawer', 'bowl 1'],
    # 'put the bowl on top of the cabinet': ['robot', 'bowl 1', 'cabinet 1'],
    # 'push the plate to the front of the stove': ['robot', 'plate 1', 'stove'],
    # 'put the cream cheese in the bowl': ['robot', 'cream cheese 1', 'bowl 1'],
    # 'turn on the stove': ['robot', 'stove'],
    # 'put the bowl on the plate': ['robot', 'bowl 1', 'plate 1'],
    # 'put the wine bottle on the rack': ['robot', 'bottle 1', 'rack 1'],

    # libero-90
    'KITCHEN_SCENE10_close_the_top_drawer_of_the_cabinet': ['robot', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE10_close_the_top_drawer_of_the_cabinet_and_put_the_black_bowl_on_top_of_it': ['robot', 'top drawer', 'cabinet 1', 'bowl 1'],
    'KITCHEN_SCENE10_put_the_black_bowl_in_the_top_drawer_of_the_cabinet': ['robot', 'bowl 1', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE10_put_the_butter_at_the_back_in_the_top_drawer_of_the_cabinet_and_close_it': ['robot', 'butter 2', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE10_put_the_butter_at_the_front_in_the_top_drawer_of_the_cabinet_and_close_it': ['robot', 'butter 1', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE10_put_the_chocolate_pudding_in_the_top_drawer_of_the_cabinet_and_close_it': ['robot', 'chocolate pudding 1', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE1_open_the_bottom_drawer_of_the_cabinet': ['robot', 'bottom drawer', 'cabinet 1'],
    'KITCHEN_SCENE1_open_the_top_drawer_of_the_cabinet': ['robot', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE1_open_the_top_drawer_of_the_cabinet_and_put_the_bowl_in_it': ['robot', 'top drawer', 'cabinet 1', 'bowl 1'],
    'KITCHEN_SCENE1_put_the_black_bowl_on_the_plate': ['robot', 'bowl 1', 'plate 1'],
    'KITCHEN_SCENE1_put_the_black_bowl_on_top_of_the_cabinet': ['robot', 'bowl 1', 'cabinet 1'],
    'KITCHEN_SCENE2_open_the_top_drawer_of_the_cabinet': ['robot', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE2_put_the_black_bowl_at_the_back_on_the_plate': ['robot', 'bowl 3', 'plate 1'],
    'KITCHEN_SCENE2_put_the_black_bowl_at_the_front_on_the_plate': ['robot', 'bowl 1', 'plate 1'],
    'KITCHEN_SCENE2_put_the_middle_black_bowl_on_the_plate': ['robot', 'bowl 2', 'plate 1'],
    'KITCHEN_SCENE2_put_the_middle_black_bowl_on_top_of_the_cabinet': ['robot', 'bowl 2', 'cabinet 1'],
    'KITCHEN_SCENE2_stack_the_black_bowl_at_the_front_on_the_black_bowl_in_the_middle': ['robot', 'bowl 1', 'bowl 2'],
    'KITCHEN_SCENE2_stack_the_middle_black_bowl_on_the_back_black_bowl': ['robot', 'bowl 2', 'bowl 3'],
    'KITCHEN_SCENE3_put_the_frying_pan_on_the_stove': ['robot', 'frying pan', 'stove'],
    'KITCHEN_SCENE3_put_the_moka_pot_on_the_stove': ['robot', 'moka pot 1', 'stove'],
    'KITCHEN_SCENE3_turn_on_the_stove': ['robot', 'stove'],
    'KITCHEN_SCENE3_turn_on_the_stove_and_put_the_frying_pan_on_it': ['robot', 'stove', 'frying pan'],
    'KITCHEN_SCENE4_close_the_bottom_drawer_of_the_cabinet': ['robot', 'bottom drawer', 'cabinet 1'],
    'KITCHEN_SCENE4_close_the_bottom_drawer_of_the_cabinet_and_open_the_top_drawer': ['robot', 'bottom drawer', 'cabinet 1', 'top drawer'],
    'KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet': ['robot', 'bowl 1', 'bottom drawer', 'cabinet 1'],
    'KITCHEN_SCENE4_put_the_black_bowl_on_top_of_the_cabinet': ['robot', 'bowl 1', 'cabinet 1'],
    'KITCHEN_SCENE4_put_the_wine_bottle_in_the_bottom_drawer_of_the_cabinet': ['robot', 'bottle 1', 'bottom drawer', 'cabinet 1'],
    'KITCHEN_SCENE4_put_the_wine_bottle_on_the_wine_rack': ['robot', 'bottle 1', 'rack 1'],
    'KITCHEN_SCENE5_close_the_top_drawer_of_the_cabinet': ['robot', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE5_put_the_black_bowl_in_the_top_drawer_of_the_cabinet': ['robot', 'bowl 1', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE5_put_the_black_bowl_on_the_plate': ['robot', 'bowl 1', 'plate 1'],
    'KITCHEN_SCENE5_put_the_black_bowl_on_top_of_the_cabinet': ['robot', 'bowl 1', 'cabinet 1'],
    'KITCHEN_SCENE5_put_the_ketchup_in_the_top_drawer_of_the_cabinet': ['robot', 'ketchup 1', 'top drawer', 'cabinet 1'],
    'KITCHEN_SCENE6_close_the_microwave': ['robot', 'microwave 1'],
    'KITCHEN_SCENE6_put_the_yellow_and_white_mug_to_the_front_of_the_white_mug': ['robot', 'white yellow mug 1', 'porcelain mug 1'],
    'KITCHEN_SCENE7_open_the_microwave': ['robot', 'microwave 1'],
    'KITCHEN_SCENE7_put_the_white_bowl_on_the_plate': ['robot', 'white bowl 1', 'plate 1'],
    'KITCHEN_SCENE7_put_the_white_bowl_to_the_right_of_the_plate': ['robot', 'white bowl 1', 'plate 1'],
    'KITCHEN_SCENE8_put_the_right_moka_pot_on_the_stove': ['robot', 'moka pot 1', 'stove'],
    'KITCHEN_SCENE8_turn_off_the_stove': ['robot', 'stove'],
    'KITCHEN_SCENE9_put_the_frying_pan_on_the_cabinet_shelf': ['robot', 'frying pan', 'wooden two layer shelf 1'],
    'KITCHEN_SCENE9_put_the_frying_pan_on_top_of_the_cabinet': ['robot', 'frying pan', 'wooden two layer shelf 1'],
    'KITCHEN_SCENE9_put_the_frying_pan_under_the_cabinet_shelf': ['robot', 'frying pan', 'wooden two layer shelf 1'],
    'KITCHEN_SCENE9_put_the_white_bowl_on_top_of_the_cabinet': ['robot', 'white bowl 1', 'wooden two layer shelf 1'],
    'KITCHEN_SCENE9_turn_on_the_stove': ['robot', 'stove'],
    'KITCHEN_SCENE9_turn_on_the_stove_and_put_the_frying_pan_on_it': ['robot', 'stove', 'frying pan'],
    'LIVING_ROOM_SCENE1_pick_up_the_alphabet_soup_and_put_it_in_the_basket': ['robot', 'alphabet soup 1', 'basket 1'],
    'LIVING_ROOM_SCENE1_pick_up_the_cream_cheese_box_and_put_it_in_the_basket': ['robot', 'cream cheese 1', 'basket 1'],
    'LIVING_ROOM_SCENE1_pick_up_the_ketchup_and_put_it_in_the_basket': ['robot', 'ketchup 1', 'basket 1'],
    'LIVING_ROOM_SCENE1_pick_up_the_tomato_sauce_and_put_it_in_the_basket': ['robot', 'tomato sauce 1', 'basket 1'],
    'LIVING_ROOM_SCENE2_pick_up_the_alphabet_soup_and_put_it_in_the_basket': ['robot', 'alphabet soup 1', 'basket 1'],
    'LIVING_ROOM_SCENE2_pick_up_the_butter_and_put_it_in_the_basket': ['robot', 'butter 1', 'basket 1'],
    'LIVING_ROOM_SCENE2_pick_up_the_milk_and_put_it_in_the_basket': ['robot', 'milk 1', 'basket 1'],
    'LIVING_ROOM_SCENE2_pick_up_the_orange_juice_and_put_it_in_the_basket': ['robot', 'orange juice 1', 'basket 1'],
    'LIVING_ROOM_SCENE2_pick_up_the_tomato_sauce_and_put_it_in_the_basket': ['robot', 'tomato sauce 1', 'basket 1'],
    'LIVING_ROOM_SCENE3_pick_up_the_alphabet_soup_and_put_it_in_the_tray': ['robot', 'alphabet soup 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE3_pick_up_the_butter_and_put_it_in_the_tray': ['robot', 'butter 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE3_pick_up_the_cream_cheese_and_put_it_in_the_tray': ['robot', 'cream cheese 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE3_pick_up_the_ketchup_and_put_it_in_the_tray': ['robot', 'ketchup 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE3_pick_up_the_tomato_sauce_and_put_it_in_the_tray': ['robot', 'tomato sauce 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE4_pick_up_the_black_bowl_on_the_left_and_put_it_in_the_tray': ['robot', 'bowl 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE4_pick_up_the_chocolate_pudding_and_put_it_in_the_tray': ['robot', 'chocolate pudding 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE4_pick_up_the_salad_dressing_and_put_it_in_the_tray': ['robot', 'new salad dressing 1', 'wooden tray 1'],
    'LIVING_ROOM_SCENE4_stack_the_left_bowl_on_the_right_bowl_and_place_them_in_the_tray': ['robot', 'bowl 1', 'bowl 2', 'wooden tray 1'],
    'LIVING_ROOM_SCENE4_stack_the_right_bowl_on_the_left_bowl_and_place_them_in_the_tray': ['robot', 'bowl 1', 'bowl 2', 'wooden tray 1'],
    'LIVING_ROOM_SCENE5_put_the_red_mug_on_the_left_plate': ['robot', 'red coffee mug 1', 'plate 1'],
    'LIVING_ROOM_SCENE5_put_the_red_mug_on_the_right_plate': ['robot', 'red coffee mug 1', 'plate 2'],
    'LIVING_ROOM_SCENE5_put_the_white_mug_on_the_left_plate': ['robot', 'porcelain mug 1', 'plate 1'],
    'LIVING_ROOM_SCENE5_put_the_yellow_and_white_mug_on_the_right_plate': ['robot', 'white yellow mug 1', 'plate 2'],
    'LIVING_ROOM_SCENE6_put_the_chocolate_pudding_to_the_left_of_the_plate': ['robot', 'chocolate pudding 1', 'plate 1'],
    'LIVING_ROOM_SCENE6_put_the_chocolate_pudding_to_the_right_of_the_plate': ['robot', 'chocolate pudding 1', 'plate 1'],
    'LIVING_ROOM_SCENE6_put_the_red_mug_on_the_plate': ['robot', 'red coffee mug 1', 'plate 1'],
    'LIVING_ROOM_SCENE6_put_the_white_mug_on_the_plate': ['robot', 'porcelain mug 1', 'plate 1'],
    'STUDY_SCENE1_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE1_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE1_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE1_pick_up_the_yellow_and_white_mug_and_place_it_to_the_right_of_the_caddy': ['robot', 'white yellow mug 1', 'desk caddy 1'],
    'STUDY_SCENE2_pick_up_the_book_and_place_it_in_the_back_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE2_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE2_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE2_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE3_pick_up_the_book_and_place_it_in_the_front_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE3_pick_up_the_book_and_place_it_in_the_left_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE3_pick_up_the_book_and_place_it_in_the_right_compartment_of_the_caddy': ['robot', 'black book 1', 'desk caddy 1'],
    'STUDY_SCENE3_pick_up_the_red_mug_and_place_it_to_the_right_of_the_caddy': ['robot', 'red coffee mug 1', 'desk caddy 1'],
    'STUDY_SCENE3_pick_up_the_white_mug_and_place_it_to_the_right_of_the_caddy': ['robot', 'porcelain mug 1', 'desk caddy 1'],
    'STUDY_SCENE4_pick_up_the_book_in_the_middle_and_place_it_on_the_cabinet_shelf': ['robot', 'black book 1', 'wooden two layer shelf 1'],
    'STUDY_SCENE4_pick_up_the_book_on_the_left_and_place_it_on_top_of_the_shelf': ['robot', 'yellow book 2', 'wooden two layer shelf 1'],
    'STUDY_SCENE4_pick_up_the_book_on_the_right_and_place_it_on_the_cabinet_shelf': ['robot', 'yellow book 1', 'wooden two layer shelf 1'],
    'STUDY_SCENE4_pick_up_the_book_on_the_right_and_place_it_under_the_cabinet_shelf': ['robot', 'yellow book 2', 'wooden two layer shelf 1'],


    # libero relation
    # 'place the black bowl behind the basket onto the left plate': ['robot', 'bowl 2', 'plate 1'],
    # 'place the black bowl in front of the basket onto the right plate': ['robot', 'bowl 1', 'plate 2'],
    # 'place the cream cheese box behind the moka pot onto the right bowl': ['robot', 'cream cheese 1', 'bowl 2'],
    # 'place the cream cheese box in front of the moka pot onto the left bowl': ['robot', 'cream cheese 2', 'bowl 1'],
    # 'place the left bowl on the right bowl': ['robot', 'bowl 1', 'bowl 2'],
    # 'place the bottle behind the cabinet onto the right plate': ['robot', 'bottle 1', 'cabinet 1', 'plate 2'],
    # 'place the bottle behind the cabinet to the left of the basket': ['robot', 'bottle 1', 'cabinet 1', 'basket 1'],
    # 'place the bottle behind the cabinet to the front of the basket': ['robot', 'bottle 1', 'cabinet 1', 'basket 1'],
    # 'put the bottle from the basket onto the cabinet': ['robot', 'bottle 1', 'cabinet 1', 'basket 1'],
    # 'place the cream cheese and the bowl into the basket': ['robot', 'cream cheese 1', 'bowl 1', 'basket 1'],
    # 'place the cream cheese behind the cabinet to the left of the basket': ['robot', 'cream cheese 1', 'basket 1'],
    # 'place the cream cheese behind the cabinet to the right of the basket': ['robot', 'cream cheese 1', 'basket 1'],
    # 'place the cream cheese behind the cabinet to the front of the basket': ['robot', 'cream cheese 1', 'basket 1'],
    # 'place the cream cheese behind the cabinet to behind the basket': ['robot', 'cream cheese 1', 'basket 1'],
    # 'place the bowl on the plate behind the cabinet': ['robot', 'bowl 1', 'plate 1', 'cabinet 1'],
    # 'stack the left bowl on the right bowl behind the cabinet': ['robot', 'bowl 1', 'bowl 2', 'cabinet 1'],
    # 'place the bottle onto the cabinet and put the left bowl behind the cabinet to the basket': ['robot', 'bottle 1', 'bowl 1', 'cabinet 1'],
    # 'put the left bowl to behind the cabinet and put the right bowl to behind the cabinet': ['robot', 'bowl 1', 'bowl 2', 'cabinet 1'],
    # 'stack the left bowl onto right bowl and put them behind the basket': ['robot', 'bowl 1', 'bowl 2', 'basket 1'],
    # 'stack the right cream cheese onto the left cream cheese and place them behind the cabinet': ['robot', 'cream cheese 1', 'cream cheese 2', 'cabinet 1'],
}
